set nocompatible
filetype off 
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'junegunn/goyo.vim'
Plugin 'junegunn/limelight.vim'

call vundle#end()
filetype plugin indent on

syntax enable
set background=dark
set linebreak
set wrap
set textwidth=80
set linespace=6
colorscheme solarized

"Associate .md with markdown not modula
au BufRead,BufNewFile *.md set filetype=markdown

"Backup files need to go mounted volume separate to where
"edited file is

"Note dir is for the swap file, bdir for backup file
set dir=/vim_tmp
set bdir=/vim_tmp

"Force UTF-8
set encoding=utf-8
set fileencoding=utf-8

"Use US english for dictionary and set a shortcut
set spelllang=en_us
nmap <silent> <leader>s :set spell!<CR>

" Shortcut for reformatting paragraphs (also not in danger of calling ed)
nnoremap <Leader>r gq}

"Uncomment following lines if you want Limelight by default.
"au User GoyoEnter Limelight
"au User GoyoLeave Limelight!
if has("gui_running")
  set guioptions-=T guioptions-=m guioptions-=r guioptions-=L
  set guifont=Monospace\ 12
  au GUIEnter * :Goyo
  "this seems to safely fullscreen in gvim but not vim
  set lines=999
  set columns=999
else
  au VimEnter * :Goyo
endif

"Stuff for asciidoc
autocmd BufRead,BufNewFile *.asciidoc
        \ setlocal filetype=asciidoc
        \ formatlistpat=^\\s*\\d\\+\\.\\s\\+\\\\|^\\s*<\\d\\+>\\s\\+\\\\|^\\s*[a-zA-Z.]\\.\\s\\+\\\\|^\\s*[ivxIVX]\\+\\.\\s\\+
        \ comments=s1:/*,ex:*/,://,b:#,:%,:XCOMM,fb:-,fb:*,fb:+,fb:.,fb:>
